name: dadonda
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # GetX
  get: ^4.6.5
  get_storage: ^2.1.1

  # Network
  http: ^0.13.5
  http_interceptor: ^1.0.2
  dartz: ^0.10.1
  json_annotation: ^4.8.0

  # UI
  pull_to_refresh: ^2.0.0
  flutter_svg: ^1.0.3
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.6.1
  pin_code_fields: ^7.4.0
  curved_navigation_bar: ^1.0.3

  # Formatting
  intl: ^0.19.0
  mask_text_input_formatter: ^2.4.0
  logger: ^1.2.2

  # Animation
  animate_do: ^3.0.2
  lottie: ^2.2.0

  #Firebase
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1

  # Dev
  alice_lightweight: ^3.4.0

  #open_link
#  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/